// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "ice_flame/internal/logic/middleware"
	_ "ice_flame/internal/logic/test"
	_ "ice_flame/internal/logic/uc_center"
)
