// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleChannel is the golang structure of table article_channel for DAO operations like Where/Data.
type ArticleChannel struct {
	g.Meta    `orm:"table:article_channel, do:true"`
	Id        interface{} //
	Name      interface{} // 栏目名称
	Remark    interface{} // 备注信息
	Sort      interface{} // 排序顺序
	Status    interface{} // 显示状态（0=显示，1=隐藏）
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
