// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleTag is the golang structure of table article_tag for DAO operations like Where/Data.
type ArticleTag struct {
	g.Meta    `orm:"table:article_tag, do:true"`
	Id        interface{} //
	Name      interface{} // tag内容
	Remark    interface{} // 备注
	Status    interface{} // 显示状态（0=显示，1=隐藏）
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
