// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleTagOrm is the golang structure of table article_tag_orm for DAO operations like Where/Data.
type ArticleTagOrm struct {
	g.Meta    `orm:"table:article_tag_orm, do:true"`
	Id        interface{} //
	TagId     interface{} // tag ID
	ArticleId interface{} // 备注
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
