// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SinglePageCategory is the golang structure of table single_page_category for DAO operations like Where/Data.
type SinglePageCategory struct {
	g.Meta    `orm:"table:single_page_category, do:true"`
	Id        interface{} //
	Name      interface{} // 分类名称
	Remark    interface{} // 备注信息
	Sort      interface{} // 排序顺序
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
