// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SinglePage is the golang structure of table single_page for DAO operations like Where/Data.
type SinglePage struct {
	g.Meta      `orm:"table:single_page, do:true"`
	Id          interface{} //
	Title       interface{} // 页面标题
	Description interface{} // 页面描述
	Keyword     interface{} // 页面关键字
	Content     interface{} // 页面内容
	Thumbnail   interface{} // 缩略图
	Click       interface{} // 点击量
	Status      interface{} // 显示状态（0=显示，1=隐藏）
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
