// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// UcAccount is the golang structure of table uc_account for DAO operations like Where/Data.
type UcAccount struct {
	g.Meta         `orm:"table:uc_account, do:true"`
	Id             interface{} //
	IdentityCardId interface{} // 关联用户身份证信息ID
	Username       interface{} // 用户名
	PasswordHash   interface{} // 用户密码
	Tel            interface{} // 用户手机号码
	Status         interface{} // 用户状态(0.启用1.停用)
	RealNameType   interface{} // 实名状态1=未实名2=已上传未审核3=审核驳回4=实名成功
	CreatedAt      interface{} //
	UpdatedAt      interface{} //
}
