// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeRole is the golang structure of table uc_employee_role for DAO operations like Where/Data.
type UcEmployeeRole struct {
	g.Meta       `orm:"table:uc_employee_role, do:true"`
	Id           interface{} // 自增ID
	Name         interface{} // 角色名称
	Remark       interface{} // 备注
	SupperMaster interface{} // 1为超级管理员模块
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
