// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeRoleRelation is the golang structure of table uc_employee_role_relation for DAO operations like Where/Data.
type UcEmployeeRoleRelation struct {
	g.Meta    `orm:"table:uc_employee_role_relation, do:true"`
	Id        interface{} //
	AccountId interface{} //
	RoleId    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
