// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeEwallet is the golang structure of table uc_employee_ewallet for DAO operations like Where/Data.
type UcEmployeeEwallet struct {
	g.Meta         `orm:"table:uc_employee_ewallet, do:true"`
	Id             interface{} //
	AccountId      interface{} // 关联员工ID
	Money          interface{} // 账户余额（单位：里）（冻结金额）
	Balance        interface{} // 上次入账余额（单位：里）
	TotalMoney     interface{} // 账户累计金额（单位：里）
	UnfreezeAmount interface{} // 解冻金额
	HashEwallet    interface{} // hash钱包
	EntryId        interface{} // 入账ID
	WithdrawId     interface{} // 提现ID
	WxOpenid       interface{} // 微信提现openid
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
