// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeEwalletOrm is the golang structure of table uc_employee_ewallet_orm for DAO operations like Where/Data.
type UcEmployeeEwalletOrm struct {
	g.Meta    `orm:"table:uc_employee_ewallet_orm, do:true"`
	Id        interface{} //
	AccountId interface{} // 关联登入ID
	UnionId   interface{} // 关联钱包充值、消费ID
	UnionType interface{} // 关联类型（1.充值、0.消费）
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
