// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeExt is the golang structure of table uc_employee_ext for DAO operations like Where/Data.
type UcEmployeeExt struct {
	g.Meta           `orm:"table:uc_employee_ext, do:true"`
	Id               interface{} //
	AccountId        interface{} // 用户id
	EmployeeSex      interface{} // 1=男2=女
	EmployeeAvatar   interface{} // 头像
	EmployeeNickname interface{} // 昵称
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
