// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeEwalletEntryLog is the golang structure of table uc_employee_ewallet_entry_log for DAO operations like Where/Data.
type UcEmployeeEwalletEntryLog struct {
	g.Meta           `orm:"table:uc_employee_ewallet_entry_log, do:true"`
	Id               interface{} //
	AccountId        interface{} // 关联员工ID
	StoreId          interface{} // 关联店铺ID
	SeparateClassify interface{} // 入账类型（1线下扫码支付 2线上 3 店铺推广会员消费分佣 4 合伙人推广会员消费分佣 5配送费 6 店铺额外合伙人分销佣金 7 WiFi分佣）
	Money            interface{} // 入账金额（单位：里）
	Balance          interface{} // 入账前余额（单位：里）
	EntryStatus      interface{} // 入账状态（99为提现驳回入账记录）
	OrderId          interface{} // 关联订单ID
	HashEntry        interface{} // 入账hash
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
