// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployee is the golang structure of table uc_employee for DAO operations like Where/Data.
type UcEmployee struct {
	g.Meta           `orm:"table:uc_employee, do:true"`
	Id               interface{} //
	AccountId        interface{} // 关联用户ID
	Name             interface{} // 姓名
	Tel              interface{} // 电话
	WxUnionId        interface{} // 关联用户unionId
	WxOpenId         interface{} // 关联用户微信OpenId
	InvitationCode   interface{} // 员工员邀请码
	InvitationQrcode interface{} // 推广二维码
	RealNameType     interface{} // 实名状态(1=未实名2=已上传未审核3=审核驳回4=实名成功)
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
