// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeEwalletWithdrawLog is the golang structure of table uc_employee_ewallet_withdraw_log for DAO operations like Where/Data.
type UcEmployeeEwalletWithdrawLog struct {
	g.Meta           `orm:"table:uc_employee_ewallet_withdraw_log, do:true"`
	Id               interface{} //
	AccountId        interface{} // 关联员工ID
	Money            interface{} // 提现金额（单位：里）
	Balance          interface{} // 提现前余额（单位：里）
	RealMoney        interface{} // 实际入账金额（单位：里）
	ChargeFee        interface{} // 入账扣点金额（单位：里）
	WithdrawalStatus interface{} // 1=申请中2=已通过待到账3=已到账99=已驳回
	RejectContent    interface{} // 驳回内容
	HashWithdraw     interface{} // 入账hash
	PartnerTradeNo   interface{} // 提现到银行卡订单号
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
