// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcPartnerLevel is the golang structure of table uc_partner_level for DAO operations like Where/Data.
type UcPartnerLevel struct {
	g.Meta    `orm:"table:uc_partner_level, do:true"`
	Id        interface{} //
	Name      interface{} // 级别名称
	Sort      interface{} // 排序
	Remark    interface{} // 备注
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
