// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemPermission is the golang structure of table uc_system_permission for DAO operations like Where/Data.
type UcSystemPermission struct {
	g.Meta    `orm:"table:uc_system_permission, do:true"`
	Id        interface{} //
	Fid       interface{} // 父级ID
	Name      interface{} // 菜单名称
	Moudule   interface{} // 对应的程序模块
	Type      interface{} // 类型（1=菜单，2=按钮）
	Status    interface{} // 程序模块状态（0=启用，1=停用）
	Remark    interface{} // 备注信息
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
