// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemPermissionRelation is the golang structure of table uc_system_permission_relation for DAO operations like Where/Data.
type UcSystemPermissionRelation struct {
	g.Meta       `orm:"table:uc_system_permission_relation, do:true"`
	Id           interface{} //
	PermissionId interface{} // 权限ID
	RoleId       interface{} // 角色ID
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
