// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMenu is the golang structure of table uc_system_menu for DAO operations like Where/Data.
type UcSystemMenu struct {
	g.Meta    `orm:"table:uc_system_menu, do:true"`
	Id        interface{} //
	Fid       interface{} // 父级ID
	Name      interface{} // 菜单名称
	Status    interface{} // 菜单状态（0=启用，停用）
	Remark    interface{} // 备注信息
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
