// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMasterRole is the golang structure of table uc_system_master_role for DAO operations like Where/Data.
type UcSystemMasterRole struct {
	g.Meta    `orm:"table:uc_system_master_role, do:true"`
	Id        interface{} // 自增ID
	Name      interface{} // 角色名称
	Remark    interface{} // 备注
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
