// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMaster is the golang structure of table uc_system_master for DAO operations like Where/Data.
type UcSystemMaster struct {
	g.Meta    `orm:"table:uc_system_master, do:true"`
	Id        interface{} // 自增ID
	AccountId interface{} // account id
	Name      interface{} //
	Tel       interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
