// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ArticleTagOrmDao is the data access object for table article_tag_orm.
type ArticleTagOrmDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns ArticleTagOrmColumns // columns contains all the column names of Table for convenient usage.
}

// ArticleTagOrmColumns defines and stores column names for table article_tag_orm.
type ArticleTagOrmColumns struct {
	Id        string //
	TagId     string // tag ID
	ArticleId string // 备注
	CreatedAt string //
	UpdatedAt string //
}

// articleTagOrmColumns holds the columns for table article_tag_orm.
var articleTagOrmColumns = ArticleTagOrmColumns{
	Id:        "id",
	TagId:     "tag_id",
	ArticleId: "article_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewArticleTagOrmDao creates and returns a new DAO object for table data access.
func NewArticleTagOrmDao() *ArticleTagOrmDao {
	return &ArticleTagOrmDao{
		group:   "default",
		table:   "article_tag_orm",
		columns: articleTagOrmColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ArticleTagOrmDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ArticleTagOrmDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ArticleTagOrmDao) Columns() ArticleTagOrmColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ArticleTagOrmDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ArticleTagOrmDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ArticleTagOrmDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
