// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcEmployeeEwalletOrmDao is the data access object for table uc_employee_ewallet_orm.
type UcEmployeeEwalletOrmDao struct {
	table   string                      // table is the underlying table name of the DAO.
	group   string                      // group is the database configuration group name of current DAO.
	columns UcEmployeeEwalletOrmColumns // columns contains all the column names of Table for convenient usage.
}

// UcEmployeeEwalletOrmColumns defines and stores column names for table uc_employee_ewallet_orm.
type UcEmployeeEwalletOrmColumns struct {
	Id        string //
	AccountId string // 关联登入ID
	UnionId   string // 关联钱包充值、消费ID
	UnionType string // 关联类型（1.充值、0.消费）
	CreatedAt string //
	UpdatedAt string //
}

// ucEmployeeEwalletOrmColumns holds the columns for table uc_employee_ewallet_orm.
var ucEmployeeEwalletOrmColumns = UcEmployeeEwalletOrmColumns{
	Id:        "id",
	AccountId: "account_id",
	UnionId:   "union_id",
	UnionType: "union_type",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUcEmployeeEwalletOrmDao creates and returns a new DAO object for table data access.
func NewUcEmployeeEwalletOrmDao() *UcEmployeeEwalletOrmDao {
	return &UcEmployeeEwalletOrmDao{
		group:   "default",
		table:   "uc_employee_ewallet_orm",
		columns: ucEmployeeEwalletOrmColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcEmployeeEwalletOrmDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcEmployeeEwalletOrmDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcEmployeeEwalletOrmDao) Columns() UcEmployeeEwalletOrmColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcEmployeeEwalletOrmDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcEmployeeEwalletOrmDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcEmployeeEwalletOrmDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
