// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcSystemMasterRoleRelationDao is the data access object for table uc_system_master_role_relation.
type UcSystemMasterRoleRelationDao struct {
	table   string                            // table is the underlying table name of the DAO.
	group   string                            // group is the database configuration group name of current DAO.
	columns UcSystemMasterRoleRelationColumns // columns contains all the column names of Table for convenient usage.
}

// UcSystemMasterRoleRelationColumns defines and stores column names for table uc_system_master_role_relation.
type UcSystemMasterRoleRelationColumns struct {
	Id        string //
	AccountId string // 管理员ID
	RoleId    string // 身份ID
	CreatedAt string //
	UpdatedAt string //
}

// ucSystemMasterRoleRelationColumns holds the columns for table uc_system_master_role_relation.
var ucSystemMasterRoleRelationColumns = UcSystemMasterRoleRelationColumns{
	Id:        "id",
	AccountId: "account_id",
	RoleId:    "role_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUcSystemMasterRoleRelationDao creates and returns a new DAO object for table data access.
func NewUcSystemMasterRoleRelationDao() *UcSystemMasterRoleRelationDao {
	return &UcSystemMasterRoleRelationDao{
		group:   "default",
		table:   "uc_system_master_role_relation",
		columns: ucSystemMasterRoleRelationColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcSystemMasterRoleRelationDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcSystemMasterRoleRelationDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcSystemMasterRoleRelationDao) Columns() UcSystemMasterRoleRelationColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcSystemMasterRoleRelationDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcSystemMasterRoleRelationDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcSystemMasterRoleRelationDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
