// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcSystemMasterRoleDao is the data access object for table uc_system_master_role.
type UcSystemMasterRoleDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns UcSystemMasterRoleColumns // columns contains all the column names of Table for convenient usage.
}

// UcSystemMasterRoleColumns defines and stores column names for table uc_system_master_role.
type UcSystemMasterRoleColumns struct {
	Id        string // 自增ID
	Name      string // 角色名称
	Remark    string // 备注
	CreatedAt string //
	UpdatedAt string //
}

// ucSystemMasterRoleColumns holds the columns for table uc_system_master_role.
var ucSystemMasterRoleColumns = UcSystemMasterRoleColumns{
	Id:        "id",
	Name:      "name",
	Remark:    "remark",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUcSystemMasterRoleDao creates and returns a new DAO object for table data access.
func NewUcSystemMasterRoleDao() *UcSystemMasterRoleDao {
	return &UcSystemMasterRoleDao{
		group:   "default",
		table:   "uc_system_master_role",
		columns: ucSystemMasterRoleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcSystemMasterRoleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcSystemMasterRoleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcSystemMasterRoleDao) Columns() UcSystemMasterRoleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcSystemMasterRoleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcSystemMasterRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcSystemMasterRoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
