// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcSystemPermissionDao is the data access object for table uc_system_permission.
type UcSystemPermissionDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns UcSystemPermissionColumns // columns contains all the column names of Table for convenient usage.
}

// UcSystemPermissionColumns defines and stores column names for table uc_system_permission.
type UcSystemPermissionColumns struct {
	Id        string //
	Fid       string // 父级ID
	Name      string // 菜单名称
	Moudule   string // 对应的程序模块
	Type      string // 类型（1=菜单，2=按钮）
	Status    string // 程序模块状态（0=启用，1=停用）
	Remark    string // 备注信息
	CreatedAt string //
	UpdatedAt string //
}

// ucSystemPermissionColumns holds the columns for table uc_system_permission.
var ucSystemPermissionColumns = UcSystemPermissionColumns{
	Id:        "id",
	Fid:       "fid",
	Name:      "name",
	Moudule:   "moudule",
	Type:      "type",
	Status:    "status",
	Remark:    "remark",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUcSystemPermissionDao creates and returns a new DAO object for table data access.
func NewUcSystemPermissionDao() *UcSystemPermissionDao {
	return &UcSystemPermissionDao{
		group:   "default",
		table:   "uc_system_permission",
		columns: ucSystemPermissionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcSystemPermissionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcSystemPermissionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcSystemPermissionDao) Columns() UcSystemPermissionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcSystemPermissionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcSystemPermissionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcSystemPermissionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
