// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcSystemMasterVisitCategoryDao is the data access object for table uc_system_master_visit_category.
type UcSystemMasterVisitCategoryDao struct {
	table   string                             // table is the underlying table name of the DAO.
	group   string                             // group is the database configuration group name of current DAO.
	columns UcSystemMasterVisitCategoryColumns // columns contains all the column names of Table for convenient usage.
}

// UcSystemMasterVisitCategoryColumns defines and stores column names for table uc_system_master_visit_category.
type UcSystemMasterVisitCategoryColumns struct {
	Id        string // 自增ID
	Title     string // 访问类型标题
	CreatedAt string //
	UpdatedAt string //
}

// ucSystemMasterVisitCategoryColumns holds the columns for table uc_system_master_visit_category.
var ucSystemMasterVisitCategoryColumns = UcSystemMasterVisitCategoryColumns{
	Id:        "id",
	Title:     "title",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUcSystemMasterVisitCategoryDao creates and returns a new DAO object for table data access.
func NewUcSystemMasterVisitCategoryDao() *UcSystemMasterVisitCategoryDao {
	return &UcSystemMasterVisitCategoryDao{
		group:   "default",
		table:   "uc_system_master_visit_category",
		columns: ucSystemMasterVisitCategoryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcSystemMasterVisitCategoryDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcSystemMasterVisitCategoryDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcSystemMasterVisitCategoryDao) Columns() UcSystemMasterVisitCategoryColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcSystemMasterVisitCategoryDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcSystemMasterVisitCategoryDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcSystemMasterVisitCategoryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
