// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcSystemMenuDao is the data access object for table uc_system_menu.
type UcSystemMenuDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns UcSystemMenuColumns // columns contains all the column names of Table for convenient usage.
}

// UcSystemMenuColumns defines and stores column names for table uc_system_menu.
type UcSystemMenuColumns struct {
	Id        string //
	Fid       string // 父级ID
	Name      string // 菜单名称
	Status    string // 菜单状态（0=启用，停用）
	Remark    string // 备注信息
	CreatedAt string //
	UpdatedAt string //
}

// ucSystemMenuColumns holds the columns for table uc_system_menu.
var ucSystemMenuColumns = UcSystemMenuColumns{
	Id:        "id",
	Fid:       "fid",
	Name:      "name",
	Status:    "status",
	Remark:    "remark",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUcSystemMenuDao creates and returns a new DAO object for table data access.
func NewUcSystemMenuDao() *UcSystemMenuDao {
	return &UcSystemMenuDao{
		group:   "default",
		table:   "uc_system_menu",
		columns: ucSystemMenuColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcSystemMenuDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcSystemMenuDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcSystemMenuDao) Columns() UcSystemMenuColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcSystemMenuDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcSystemMenuDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcSystemMenuDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
