// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UcSystemMasterVisitorLogsDao is the data access object for table uc_system_master_visitor_logs.
type UcSystemMasterVisitorLogsDao struct {
	table   string                           // table is the underlying table name of the DAO.
	group   string                           // group is the database configuration group name of current DAO.
	columns UcSystemMasterVisitorLogsColumns // columns contains all the column names of Table for convenient usage.
}

// UcSystemMasterVisitorLogsColumns defines and stores column names for table uc_system_master_visitor_logs.
type UcSystemMasterVisitorLogsColumns struct {
	Id            string // 自增ID
	AccountId     string // 关联用户ID
	OsCategory    string // 系统访问类型（1=web端，2=android端，3=IOS端）
	VisitCategory string // 访问类型
	UnionId       string // 关联ID
	Description   string // 访问信息描述
	IpLong        string //
	Ip            string //
	CreatedAt     string //
	UpdatedAt     string //
}

// ucSystemMasterVisitorLogsColumns holds the columns for table uc_system_master_visitor_logs.
var ucSystemMasterVisitorLogsColumns = UcSystemMasterVisitorLogsColumns{
	Id:            "id",
	AccountId:     "account_id",
	OsCategory:    "os_category",
	VisitCategory: "visit_category",
	UnionId:       "union_id",
	Description:   "description",
	IpLong:        "ip_long",
	Ip:            "ip",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// NewUcSystemMasterVisitorLogsDao creates and returns a new DAO object for table data access.
func NewUcSystemMasterVisitorLogsDao() *UcSystemMasterVisitorLogsDao {
	return &UcSystemMasterVisitorLogsDao{
		group:   "default",
		table:   "uc_system_master_visitor_logs",
		columns: ucSystemMasterVisitorLogsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UcSystemMasterVisitorLogsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UcSystemMasterVisitorLogsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UcSystemMasterVisitorLogsDao) Columns() UcSystemMasterVisitorLogsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UcSystemMasterVisitorLogsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UcSystemMasterVisitorLogsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UcSystemMasterVisitorLogsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
