// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"ice_flame/internal/model/article"
)

type (
	ISinglePage interface {
		CreateCategory(ctx context.Context, in article.CreateSinglePageCategoryInput) (code int32, message string, err error)
		GetCategoryById(ctx context.Context, id uint16) (code int32, message string, output *article.SinglePageCategoryOutput, err error)
		ModifyCategoryById(ctx context.Context, in article.ModifySinglePageCategoryInput) (code int32, message string, err error)
		ListCategoryById(ctx context.Context)
		DeleteCategoryById(ctx context.Context, id uint16)
		GetCategoryAll(ctx context.Context)
	}
)

var (
	localSinglePage ISinglePage
)

func SinglePage() ISinglePage {
	if localSinglePage == nil {
		panic("implement not found for interface ISinglePage, forgot register?")
	}
	return localSinglePage
}

func RegisterSinglePage(i ISinglePage) {
	localSinglePage = i
}
