// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"ice_flame/internal/model/article"
)

type (
	ISinglePage interface {
		Create(ctx context.Context, in article.CreateSinglePageInput) (code int32, message string, err error)
		GetById(ctx context.Context, id uint32) (code int32, message string, output *article.SinglePageOutput, err error)
		ModifyById(ctx context.Context, in article.ModifySinglePageInput) (code int32, message string, err error)
		List(ctx context.Context, in article.ListSinglePageInput) (code int32, message string, output []*article.SinglePageOutput, err error)
		Delete(ctx context.Context, id uint16) (code int32, message string, err error)
	}
)

var (
	localSinglePage ISinglePage
)

func SinglePage() ISinglePage {
	if localSinglePage == nil {
		panic("implement not found for interface ISinglePage, forgot register?")
	}
	return localSinglePage
}

func RegisterSinglePage(i ISinglePage) {
	localSinglePage = i
}
