// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	ISinglePage interface {
		CreateCategory(ctx context.Context)
	}
)

var (
	localSinglePage ISinglePage
)

func SinglePage() ISinglePage {
	if localSinglePage == nil {
		panic("implement not found for interface ISinglePage, forgot register?")
	}
	return localSinglePage
}

func RegisterSinglePage(i ISinglePage) {
	localSinglePage = i
}
