// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"ice_flame/internal/model"
)

type (
	IDBTest interface {
		TestInsert(ctx context.Context, in model.TestDBInsertInput) (code int32, message string, err error)
		TestInsertAndGetId(ctx context.Context, in model.TestDBInsertInput) (code int32, message string, lastInsertId int64, err error)
		TestGetStructById(ctx context.Context, in model.TestGetByIdInput, output interface{}) (code int32, message string, err error)
		TestGetStructGCacheById(ctx context.Context, in model.TestGetByIdInput, output interface{}) (code int32, message string, err error)
		TestGetStructRCacheById(ctx context.Context, in model.TestGetByIdInput, output interface{}) (code int32, message string, err error)
		TestGetMapById(ctx context.Context, in model.TestGetByIdInput) (code int32, message string, output interface{}, err error)
		TestGetMapGCacheById(ctx context.Context, in model.TestGetByIdInput) (code int32, message string, output interface{}, err error)
		TestGetMapRCacheById(ctx context.Context, in model.TestGetByIdInput) (code int32, message string, output interface{}, err error)
		TestGetStructByIds(ctx context.Context, in model.TestGetByIdsInput, output interface{}) (code int32, message string, err error)
		TestGetMapByIds(ctx context.Context, in model.TestGetByIdsInput) (code int32, message string, output interface{}, err error)
		TestGetOneStructByWhere(ctx context.Context, in model.TestGetOneByWhereInput, output interface{}) (code int32, message string, err error)
		TestGetOneMapByWhere(ctx context.Context, in model.TestGetOneByWhereInput) (code int32, message string, output interface{}, err error)
		TestDBGetAllStructByWhere(ctx context.Context, in model.TestGetAllByWhereInput, output interface{}) (code int32, message string, err error)
		TestDBGetAllMapByWhere(ctx context.Context, in model.TestGetAllByWhereInput) (code int32, message string, output interface{}, err error)
		TestDBModifyById(ctx context.Context, in model.TestModifyByIdInput) (code int32, message string, err error)
		TestDBModifyGCacheById(ctx context.Context, in model.TestModifyByIdInput) (code int32, message string, err error)
		TestDBModifyRCacheById(ctx context.Context, in model.TestModifyByIdInput) (code int32, message string, err error)
		TestDBModifyByWhere(ctx context.Context, in model.TestModifyByWhereInput) (code int32, message string, err error)
		TestDBDelById(ctx context.Context, in model.TestDelByIdInput) (code int32, message string, err error)
		TestDBDelByIds(ctx context.Context, in model.TestDelByIdsInput) (code int32, message string, err error)
		TestDBDelByWhere(ctx context.Context, in model.TestDelByWhereInput) (code int32, message string, err error)
		TestDBModifyIncById(ctx context.Context, in model.TestModifyIncByIdInput) (code int32, message string, err error)
		TestDBModifyDecById(ctx context.Context, in model.TestModifyDecByIdInput) (code int32, message string, err error)
		TestDBModifyIncByWhere(ctx context.Context, in model.TestModifyIncByWhereInput) (code int32, message string, err error)
		TestDBModifyDecByWhere(ctx context.Context, in model.TestModifyDecByWhereInput) (code int32, message string, err error)
	}
	IRedisCacheTest interface {
		TestExistsSetData(ctx context.Context, in model.TestExistsSetDataInput) (code int32, message string, err error)
	}
)

var (
	localDBTest         IDBTest
	localRedisCacheTest IRedisCacheTest
)

func DBTest() IDBTest {
	if localDBTest == nil {
		panic("implement not found for interface IDBTest, forgot register?")
	}
	return localDBTest
}

func RegisterDBTest(i IDBTest) {
	localDBTest = i
}

func RedisCacheTest() IRedisCacheTest {
	if localRedisCacheTest == nil {
		panic("implement not found for interface IRedisCacheTest, forgot register?")
	}
	return localRedisCacheTest
}

func RegisterRedisCacheTest(i IRedisCacheTest) {
	localRedisCacheTest = i
}
