// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalArticleCategoryDao is internal type for wrapping internal DAO implements.
type internalArticleCategoryDao = *internal.ArticleCategoryDao

// articleCategoryDao is the data access object for table article_category.
// You can define custom methods on it to extend its functionality as you wish.
type articleCategoryDao struct {
	internalArticleCategoryDao
}

var (
	// ArticleCategory is globally public accessible object for table article_category operations.
	ArticleCategory = articleCategoryDao{
		internal.NewArticleCategoryDao(),
	}
)

// Fill with you ideas below.
