// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalArticleTagDao is internal type for wrapping internal DAO implements.
type internalArticleTagDao = *internal.ArticleTagDao

// articleTagDao is the data access object for table article_tag.
// You can define custom methods on it to extend its functionality as you wish.
type articleTagDao struct {
	internalArticleTagDao
}

var (
	// ArticleTag is globally public accessible object for table article_tag operations.
	ArticleTag = articleTagDao{
		internal.NewArticleTagDao(),
	}
)

// Fill with you ideas below.
