// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalArticleTagOrmDao is internal type for wrapping internal DAO implements.
type internalArticleTagOrmDao = *internal.ArticleTagOrmDao

// articleTagOrmDao is the data access object for table article_tag_orm.
// You can define custom methods on it to extend its functionality as you wish.
type articleTagOrmDao struct {
	internalArticleTagOrmDao
}

var (
	// ArticleTagOrm is globally public accessible object for table article_tag_orm operations.
	ArticleTagOrm = articleTagOrmDao{
		internal.NewArticleTagOrmDao(),
	}
)

// Fill with you ideas below.
