// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalArticleChannelDao is internal type for wrapping internal DAO implements.
type internalArticleChannelDao = *internal.ArticleChannelDao

// articleChannelDao is the data access object for table article_channel.
// You can define custom methods on it to extend its functionality as you wish.
type articleChannelDao struct {
	internalArticleChannelDao
}

var (
	// ArticleChannel is globally public accessible object for table article_channel operations.
	ArticleChannel = articleChannelDao{
		internal.NewArticleChannelDao(),
	}
)

// Fill with you ideas below.
