// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalDbTestDao is internal type for wrapping internal DAO implements.
type internalDbTestDao = *internal.DbTestDao

// dbTestDao is the data access object for table db_test.
// You can define custom methods on it to extend its functionality as you wish.
type dbTestDao struct {
	internalDbTestDao
}

var (
	// DbTest is globally public accessible object for table db_test operations.
	DbTest = dbTestDao{
		internal.NewDbTestDao(),
	}
)

// Fill with you ideas below.
