// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalSinglePageDao is internal type for wrapping internal DAO implements.
type internalSinglePageDao = *internal.SinglePageDao

// singlePageDao is the data access object for table single_page.
// You can define custom methods on it to extend its functionality as you wish.
type singlePageDao struct {
	internalSinglePageDao
}

var (
	// SinglePage is globally public accessible object for table single_page operations.
	SinglePage = singlePageDao{
		internal.NewSinglePageDao(),
	}
)

// Fill with you ideas below.
