// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcEmployeeEwalletWithdrawLogDao is internal type for wrapping internal DAO implements.
type internalUcEmployeeEwalletWithdrawLogDao = *internal.UcEmployeeEwalletWithdrawLogDao

// ucEmployeeEwalletWithdrawLogDao is the data access object for table uc_employee_ewallet_withdraw_log.
// You can define custom methods on it to extend its functionality as you wish.
type ucEmployeeEwalletWithdrawLogDao struct {
	internalUcEmployeeEwalletWithdrawLogDao
}

var (
	// UcEmployeeEwalletWithdrawLog is globally public accessible object for table uc_employee_ewallet_withdraw_log operations.
	UcEmployeeEwalletWithdrawLog = ucEmployeeEwalletWithdrawLogDao{
		internal.NewUcEmployeeEwalletWithdrawLogDao(),
	}
)

// Fill with you ideas below.
