// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcEmployeeRoleDao is internal type for wrapping internal DAO implements.
type internalUcEmployeeRoleDao = *internal.UcEmployeeRoleDao

// ucEmployeeRoleDao is the data access object for table uc_employee_role.
// You can define custom methods on it to extend its functionality as you wish.
type ucEmployeeRoleDao struct {
	internalUcEmployeeRoleDao
}

var (
	// UcEmployeeRole is globally public accessible object for table uc_employee_role operations.
	UcEmployeeRole = ucEmployeeRoleDao{
		internal.NewUcEmployeeRoleDao(),
	}
)

// Fill with you ideas below.
