// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcEmployeeEwalletEntryLogDao is internal type for wrapping internal DAO implements.
type internalUcEmployeeEwalletEntryLogDao = *internal.UcEmployeeEwalletEntryLogDao

// ucEmployeeEwalletEntryLogDao is the data access object for table uc_employee_ewallet_entry_log.
// You can define custom methods on it to extend its functionality as you wish.
type ucEmployeeEwalletEntryLogDao struct {
	internalUcEmployeeEwalletEntryLogDao
}

var (
	// UcEmployeeEwalletEntryLog is globally public accessible object for table uc_employee_ewallet_entry_log operations.
	UcEmployeeEwalletEntryLog = ucEmployeeEwalletEntryLogDao{
		internal.NewUcEmployeeEwalletEntryLogDao(),
	}
)

// Fill with you ideas below.
