// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcEmployeeEwalletDao is internal type for wrapping internal DAO implements.
type internalUcEmployeeEwalletDao = *internal.UcEmployeeEwalletDao

// ucEmployeeEwalletDao is the data access object for table uc_employee_ewallet.
// You can define custom methods on it to extend its functionality as you wish.
type ucEmployeeEwalletDao struct {
	internalUcEmployeeEwalletDao
}

var (
	// UcEmployeeEwallet is globally public accessible object for table uc_employee_ewallet operations.
	UcEmployeeEwallet = ucEmployeeEwalletDao{
		internal.NewUcEmployeeEwalletDao(),
	}
)

// Fill with you ideas below.
