// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcEmployeeEwalletOrmDao is internal type for wrapping internal DAO implements.
type internalUcEmployeeEwalletOrmDao = *internal.UcEmployeeEwalletOrmDao

// ucEmployeeEwalletOrmDao is the data access object for table uc_employee_ewallet_orm.
// You can define custom methods on it to extend its functionality as you wish.
type ucEmployeeEwalletOrmDao struct {
	internalUcEmployeeEwalletOrmDao
}

var (
	// UcEmployeeEwalletOrm is globally public accessible object for table uc_employee_ewallet_orm operations.
	UcEmployeeEwalletOrm = ucEmployeeEwalletOrmDao{
		internal.NewUcEmployeeEwalletOrmDao(),
	}
)

// Fill with you ideas below.
