// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcEmployeeRoleRelationDao is internal type for wrapping internal DAO implements.
type internalUcEmployeeRoleRelationDao = *internal.UcEmployeeRoleRelationDao

// ucEmployeeRoleRelationDao is the data access object for table uc_employee_role_relation.
// You can define custom methods on it to extend its functionality as you wish.
type ucEmployeeRoleRelationDao struct {
	internalUcEmployeeRoleRelationDao
}

var (
	// UcEmployeeRoleRelation is globally public accessible object for table uc_employee_role_relation operations.
	UcEmployeeRoleRelation = ucEmployeeRoleRelationDao{
		internal.NewUcEmployeeRoleRelationDao(),
	}
)

// Fill with you ideas below.
