// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcPartnerLevelDao is internal type for wrapping internal DAO implements.
type internalUcPartnerLevelDao = *internal.UcPartnerLevelDao

// ucPartnerLevelDao is the data access object for table uc_partner_level.
// You can define custom methods on it to extend its functionality as you wish.
type ucPartnerLevelDao struct {
	internalUcPartnerLevelDao
}

var (
	// UcPartnerLevel is globally public accessible object for table uc_partner_level operations.
	UcPartnerLevel = ucPartnerLevelDao{
		internal.NewUcPartnerLevelDao(),
	}
)

// Fill with you ideas below.
