// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcSystemPermissionDao is internal type for wrapping internal DAO implements.
type internalUcSystemPermissionDao = *internal.UcSystemPermissionDao

// ucSystemPermissionDao is the data access object for table uc_system_permission.
// You can define custom methods on it to extend its functionality as you wish.
type ucSystemPermissionDao struct {
	internalUcSystemPermissionDao
}

var (
	// UcSystemPermission is globally public accessible object for table uc_system_permission operations.
	UcSystemPermission = ucSystemPermissionDao{
		internal.NewUcSystemPermissionDao(),
	}
)

// Fill with you ideas below.
