// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcSystemMasterVisitorLogsDao is internal type for wrapping internal DAO implements.
type internalUcSystemMasterVisitorLogsDao = *internal.UcSystemMasterVisitorLogsDao

// ucSystemMasterVisitorLogsDao is the data access object for table uc_system_master_visitor_logs.
// You can define custom methods on it to extend its functionality as you wish.
type ucSystemMasterVisitorLogsDao struct {
	internalUcSystemMasterVisitorLogsDao
}

var (
	// UcSystemMasterVisitorLogs is globally public accessible object for table uc_system_master_visitor_logs operations.
	UcSystemMasterVisitorLogs = ucSystemMasterVisitorLogsDao{
		internal.NewUcSystemMasterVisitorLogsDao(),
	}
)

// Fill with you ideas below.
