// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcSystemMenuDao is internal type for wrapping internal DAO implements.
type internalUcSystemMenuDao = *internal.UcSystemMenuDao

// ucSystemMenuDao is the data access object for table uc_system_menu.
// You can define custom methods on it to extend its functionality as you wish.
type ucSystemMenuDao struct {
	internalUcSystemMenuDao
}

var (
	// UcSystemMenu is globally public accessible object for table uc_system_menu operations.
	UcSystemMenu = ucSystemMenuDao{
		internal.NewUcSystemMenuDao(),
	}
)

// Fill with you ideas below.
