// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcSystemPermissionRelationDao is internal type for wrapping internal DAO implements.
type internalUcSystemPermissionRelationDao = *internal.UcSystemPermissionRelationDao

// ucSystemPermissionRelationDao is the data access object for table uc_system_permission_relation.
// You can define custom methods on it to extend its functionality as you wish.
type ucSystemPermissionRelationDao struct {
	internalUcSystemPermissionRelationDao
}

var (
	// UcSystemPermissionRelation is globally public accessible object for table uc_system_permission_relation operations.
	UcSystemPermissionRelation = ucSystemPermissionRelationDao{
		internal.NewUcSystemPermissionRelationDao(),
	}
)

// Fill with you ideas below.
