// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcSystemMasterVisitCategoryDao is internal type for wrapping internal DAO implements.
type internalUcSystemMasterVisitCategoryDao = *internal.UcSystemMasterVisitCategoryDao

// ucSystemMasterVisitCategoryDao is the data access object for table uc_system_master_visit_category.
// You can define custom methods on it to extend its functionality as you wish.
type ucSystemMasterVisitCategoryDao struct {
	internalUcSystemMasterVisitCategoryDao
}

var (
	// UcSystemMasterVisitCategory is globally public accessible object for table uc_system_master_visit_category operations.
	UcSystemMasterVisitCategory = ucSystemMasterVisitCategoryDao{
		internal.NewUcSystemMasterVisitCategoryDao(),
	}
)

// Fill with you ideas below.
