// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ice_flame/internal/dao/internal"
)

// internalUcSystemMasterDao is internal type for wrapping internal DAO implements.
type internalUcSystemMasterDao = *internal.UcSystemMasterDao

// ucSystemMasterDao is the data access object for table uc_system_master.
// You can define custom methods on it to extend its functionality as you wish.
type ucSystemMasterDao struct {
	internalUcSystemMasterDao
}

var (
	// UcSystemMaster is globally public accessible object for table uc_system_master operations.
	UcSystemMaster = ucSystemMasterDao{
		internal.NewUcSystemMasterDao(),
	}
)

// Fill with you ideas below.
