// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleChannel is the golang structure for table article_channel.
type ArticleChannel struct {
	Id        uint        `json:"id"         ` //
	Name      string      `json:"name"       ` // 栏目名称
	Remark    string      `json:"remark"     ` // 备注信息
	Sort      uint        `json:"sort"       ` // 排序顺序
	Status    uint        `json:"status"     ` // 显示状态（0=显示，1=隐藏）
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
