// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleTagOrm is the golang structure for table article_tag_orm.
type ArticleTagOrm struct {
	Id        uint        `json:"id"         ` //
	TagId     int         `json:"tag_id"     ` // tag ID
	ArticleId int         `json:"article_id" ` // 备注
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
