// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	Id          uint        `json:"id"          ` //
	CategoryId  uint        `json:"category_id" ` // 分类ID
	ChannelId   uint        `json:"channel_id"  ` // 栏目ID
	Title       string      `json:"title"       ` // 标题
	Keyword     string      `json:"keyword"     ` // 关键字
	Description string      `json:"description" ` // 描述
	Link        string      `json:"link"        ` // 文章链接
	Author      string      `json:"author"      ` // 作者
	Tags        string      `json:"tags"        ` // Tag标签
	PubDate     *gtime.Time `json:"pub_date"    ` // 发布时间
	Summary     string      `json:"summary"     ` // 摘要
	Content     string      `json:"content"     ` // 内容
	Thumbnail   string      `json:"thumbnail"   ` // 缩略图
	Click       uint        `json:"click"       ` // 点击量
	Status      int         `json:"status"      ` // 显示状态（0=显示，1=隐藏）
	CreatedAt   *gtime.Time `json:"created_at"  ` //
	UpdatedAt   *gtime.Time `json:"updated_at"  ` //
}
