// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// DbTest is the golang structure for table db_test.
type DbTest struct {
	Id       uint   `json:"id"        ` // 自增ID
	TestData string `json:"test_data" ` // 数据
	Title    string `json:"title"     ` // 标题
}
