// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SinglePageCategory is the golang structure for table single_page_category.
type SinglePageCategory struct {
	Id        uint        `json:"id"         ` //
	Name      string      `json:"name"       ` // 分类名称
	Remark    string      `json:"remark"     ` // 备注信息
	Sort      uint        `json:"sort"       ` // 排序顺序
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
