// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UcAccount is the golang structure for table uc_account.
type UcAccount struct {
	Id             uint   `json:"id"               ` //
	IdentityCardId uint   `json:"identity_card_id" ` // 关联用户身份证信息ID
	Username       string `json:"username"         ` // 用户名
	PasswordHash   string `json:"password_hash"    ` // 用户密码
	Tel            string `json:"tel"              ` // 用户手机号码
	Status         int    `json:"status"           ` // 用户状态(0.启用1.停用)
	RealNameType   int    `json:"real_name_type"   ` // 实名状态1=未实名2=已上传未审核3=审核驳回4=实名成功
	CreatedAt      uint   `json:"created_at"       ` //
	UpdatedAt      uint   `json:"updated_at"       ` //
}
