// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployee is the golang structure for table uc_employee.
type UcEmployee struct {
	Id               uint        `json:"id"                ` //
	AccountId        uint        `json:"account_id"        ` // 关联用户ID
	Name             string      `json:"name"              ` // 姓名
	Tel              string      `json:"tel"               ` // 电话
	WxUnionId        string      `json:"wx_union_id"       ` // 关联用户unionId
	WxOpenId         string      `json:"wx_open_id"        ` // 关联用户微信OpenId
	InvitationCode   string      `json:"invitation_code"   ` // 员工员邀请码
	InvitationQrcode string      `json:"invitation_qrcode" ` // 推广二维码
	RealNameType     uint        `json:"real_name_type"    ` // 实名状态(1=未实名2=已上传未审核3=审核驳回4=实名成功)
	CreatedAt        *gtime.Time `json:"created_at"        ` //
	UpdatedAt        *gtime.Time `json:"updated_at"        ` //
}
