// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeRoleRelation is the golang structure for table uc_employee_role_relation.
type UcEmployeeRoleRelation struct {
	Id        uint        `json:"id"         ` //
	AccountId uint        `json:"account_id" ` //
	RoleId    int         `json:"role_id"    ` //
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
