// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeExt is the golang structure for table uc_employee_ext.
type UcEmployeeExt struct {
	Id               uint        `json:"id"                ` //
	AccountId        int         `json:"account_id"        ` // 用户id
	EmployeeSex      uint        `json:"employee_sex"      ` // 1=男2=女
	EmployeeAvatar   string      `json:"employee_avatar"   ` // 头像
	EmployeeNickname string      `json:"employee_nickname" ` // 昵称
	CreatedAt        *gtime.Time `json:"created_at"        ` //
	UpdatedAt        *gtime.Time `json:"updated_at"        ` //
}
