// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeEwalletEntryLog is the golang structure for table uc_employee_ewallet_entry_log.
type UcEmployeeEwalletEntryLog struct {
	Id               uint        `json:"id"                ` //
	AccountId        uint        `json:"account_id"        ` // 关联员工ID
	StoreId          uint        `json:"store_id"          ` // 关联店铺ID
	SeparateClassify uint        `json:"separate_classify" ` // 入账类型（1线下扫码支付 2线上 3 店铺推广会员消费分佣 4 合伙人推广会员消费分佣 5配送费 6 店铺额外合伙人分销佣金 7 WiFi分佣）
	Money            uint        `json:"money"             ` // 入账金额（单位：里）
	Balance          int         `json:"balance"           ` // 入账前余额（单位：里）
	EntryStatus      uint        `json:"entry_status"      ` // 入账状态（99为提现驳回入账记录）
	OrderId          uint        `json:"order_id"          ` // 关联订单ID
	HashEntry        string      `json:"hash_entry"        ` // 入账hash
	CreatedAt        *gtime.Time `json:"created_at"        ` //
	UpdatedAt        *gtime.Time `json:"updated_at"        ` //
}
