// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcEmployeeEwalletWithdrawLog is the golang structure for table uc_employee_ewallet_withdraw_log.
type UcEmployeeEwalletWithdrawLog struct {
	Id               uint        `json:"id"                ` //
	AccountId        uint        `json:"account_id"        ` // 关联员工ID
	Money            uint        `json:"money"             ` // 提现金额（单位：里）
	Balance          int         `json:"balance"           ` // 提现前余额（单位：里）
	RealMoney        int         `json:"real_money"        ` // 实际入账金额（单位：里）
	ChargeFee        int         `json:"charge_fee"        ` // 入账扣点金额（单位：里）
	WithdrawalStatus int         `json:"withdrawal_status" ` // 1=申请中2=已通过待到账3=已到账99=已驳回
	RejectContent    string      `json:"reject_content"    ` // 驳回内容
	HashWithdraw     string      `json:"hash_withdraw"     ` // 入账hash
	PartnerTradeNo   string      `json:"partner_trade_no"  ` // 提现到银行卡订单号
	CreatedAt        *gtime.Time `json:"created_at"        ` //
	UpdatedAt        *gtime.Time `json:"updated_at"        ` //
}
