// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcPartnerLevel is the golang structure for table uc_partner_level.
type UcPartnerLevel struct {
	Id        uint        `json:"id"         ` //
	Name      string      `json:"name"       ` // 级别名称
	Sort      uint        `json:"sort"       ` // 排序
	Remark    string      `json:"remark"     ` // 备注
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
