// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemPermission is the golang structure for table uc_system_permission.
type UcSystemPermission struct {
	Id        uint        `json:"id"         ` //
	Fid       uint        `json:"fid"        ` // 父级ID
	Name      string      `json:"name"       ` // 菜单名称
	Moudule   string      `json:"moudule"    ` // 对应的程序模块
	Type      int         `json:"type"       ` // 类型（1=菜单，2=按钮）
	Status    uint        `json:"status"     ` // 程序模块状态（0=启用，1=停用）
	Remark    string      `json:"remark"     ` // 备注信息
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
