// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMaster is the golang structure for table uc_system_master.
type UcSystemMaster struct {
	Id        uint        `json:"id"         ` // 自增ID
	AccountId uint        `json:"account_id" ` // account id
	Name      string      `json:"name"       ` //
	Tel       string      `json:"tel"        ` //
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
