// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemPermissionExclude is the golang structure for table uc_system_permission_exclude.
type UcSystemPermissionExclude struct {
	Id        uint        `json:"id"         ` //
	Name      string      `json:"name"       ` // 菜单名称
	Module    string      `json:"module"     ` // 对应的程序模块
	Uri       string      `json:"uri"        ` // 对应的URI地址
	Remark    string      `json:"remark"     ` // 备注信息
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
