// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMasterRoleRelation is the golang structure for table uc_system_master_role_relation.
type UcSystemMasterRoleRelation struct {
	Id        int         `json:"id"         ` //
	AccountId int         `json:"account_id" ` // 管理员ID
	RoleId    int         `json:"role_id"    ` // 身份ID
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
