// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMasterRole is the golang structure for table uc_system_master_role.
type UcSystemMasterRole struct {
	Id        int         `json:"id"         ` // 自增ID
	Name      string      `json:"name"       ` // 角色名称
	Remark    string      `json:"remark"     ` // 备注
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
