// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemMasterVisitCategory is the golang structure for table uc_system_master_visit_category.
type UcSystemMasterVisitCategory struct {
	Id        uint        `json:"id"         ` // 自增ID
	Title     string      `json:"title"      ` // 访问类型标题
	CreatedAt *gtime.Time `json:"created_at" ` //
	UpdatedAt *gtime.Time `json:"updated_at" ` //
}
