// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UcSystemPermissionRelation is the golang structure for table uc_system_permission_relation.
type UcSystemPermissionRelation struct {
	Id           uint        `json:"id"            ` //
	PermissionId uint        `json:"permission_id" ` // 权限ID
	RoleId       uint        `json:"role_id"       ` // 角色ID
	CreatedAt    *gtime.Time `json:"created_at"    ` //
	UpdatedAt    *gtime.Time `json:"updated_at"    ` //
}
